# This file is generated by termdown's release workflow from
# .github/homebrew/termdown.rb.template. Do not edit the tap copy by hand.
class Termdown < Formula
  desc "Terminal Markdown browser written in pure Swift"
  homepage "https://github.com/dsaad68/termdown"
  version "0.1.7"
  license "MIT"

  on_macos do
    url "https://github.com/dsaad68/termdown/releases/download/v0.1.7/termdown-v0.1.7-macos.tar.gz"
    sha256 "64d024b635c775146d144f6311de7f78e17ed21ec000dd7f2e32ad822ed34638"
  end

  on_linux do
    url "https://github.com/dsaad68/termdown/releases/download/v0.1.7/termdown-v0.1.7-linux-x86_64.tar.gz"
    sha256 "356cca15b6a6227e11a322870cf6295634470d21e5ddcc49c1400e5240f911c1"
  end

  def install
    bin.install "termdown"
  end

  test do
    assert_match "termdown 0.1.7", shell_output("#{bin}/termdown --version")
  end
end
