# This file is generated by termdown's release workflow from
# .github/homebrew/termdown.rb.template. Do not edit the tap copy by hand.
class Termdown < Formula
  desc "Terminal Markdown browser written in pure Swift"
  homepage "https://github.com/dsaad68/termdown"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/dsaad68/termdown/releases/download/v0.1.0/termdown-v0.1.0-macos.tar.gz"
    sha256 "284e6ce148481923425f669749d257b614db738f5330d4e606e3c0121542184b"
  end

  on_linux do
    url "https://github.com/dsaad68/termdown/releases/download/v0.1.0/termdown-v0.1.0-linux-x86_64.tar.gz"
    sha256 "772a0a739bbe03a08bdbda9947e638a13efc98e151befc9f81c1201a6c42e998"
  end

  def install
    bin.install "termdown"
  end

  test do
    assert_match "termdown 0.1.0", shell_output("#{bin}/termdown --version")
  end
end
