# This file is generated by termdown's release workflow from
# .github/homebrew/termdown.rb.template. Do not edit the tap copy by hand.
class Termdown < Formula
  desc "Terminal Markdown browser written in pure Swift"
  homepage "https://github.com/dsaad68/termdown"
  version "0.1.9"
  license "MIT"

  on_macos do
    url "https://github.com/dsaad68/termdown/releases/download/v0.1.9/termdown-v0.1.9-macos.tar.gz"
    sha256 "ce7f2661b0ff4ee1a271cf9083fbc1b18087abed520138a5080c4b236c22545c"
  end

  on_linux do
    url "https://github.com/dsaad68/termdown/releases/download/v0.1.9/termdown-v0.1.9-linux-x86_64.tar.gz"
    sha256 "98351991a2db5ff95f466e0303fbd4f2a8ad6115aceb62abec02011f73b194d5"
  end

  def install
    bin.install "termdown"
  end

  test do
    assert_match "termdown 0.1.9", shell_output("#{bin}/termdown --version")
  end
end
